---
title: "Proyecto entrega 3"
output: 
  html_document:
    code_folding: hide
date: <font size="2">2024-03-12</font> 
author:
   <font size="2"> - Antonio Lomelí Ureña<br></font>
   <font size="2"> - Carolina Martínez<br></font> 
   <font size="2"> - Enrique Tonatiuh Pérez Cortés<br></font> 
   <font size="2"> - Eddie Aguilar</font> 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Introducción





## Cálculo de correlación 
```{r}
Emisoras <- read.csv("Emisoras_Completo2.csv")
```

```{r}
library(PerformanceAnalytics)
library(quantmod)
library(tidyverse)
clave <- "FEMSAUBD.MX"
datos <- new.env()
getSymbols(clave, warnings = FALSE, env=datos)
precio <- datos[[clave]][,6]
Rend <- na.omit(diff(log(na.omit(precio))))
```
### Comparación con el mercado
```{r}
getSymbols("^MXX")
rend_mercado <- na.omit(diff(log(na.omit(MXX$MXX.Adjusted))))

datos <- na.omit(merge.xts(Rend, rend_mercado))
```

```{r}
cor(datos)
cov(datos)
```


```{r}
chart.Correlation(datos)
```

### Correlación
```{r, message=FALSE, warning=FALSE}
lista <- as.matrix(Emisoras)
n <- length(lista)
mat_cor_a <- matrix(nrow=n, ncol=2)
datos_cor <- new.env()
for (i in 1:n) {
  clave <- lista[i]
  getSymbols(clave, env=datos_cor, warnings = FALSE)
  precio2 <- datos_cor[[clave]][,6]
  rendimiento2 <- na.omit(diff(log(na.omit(precio2))))
  datos_cor2 <- na.omit(merge.xts(Rend, rendimiento2))
  ro <- as.numeric(cor(datos_cor2)[1,2])
  mat_cor_a[i,2] <- ro
  mat_cor_a[i,1] <- clave
}
```


Primero calculamos la correlación con todos los activos.
```{r}
mat_cor_a <- as.data.frame(mat_cor_a)
names(mat_cor_a) <- c("Activo", "Ro")
arrange(mat_cor_a, Ro)
```

Se destacan los 5 activos con mayor correlación con la acción base de este proyecto. 

------ AGREGAR EL MERCADO ------------------------------------------------------------
```{r}
mat_cor_a$Ro <- as.numeric(mat_cor_a$Ro)
mat_cor_a_sorted <- mat_cor_a %>%
  arrange(desc(Ro))
correlated <- head(mat_cor_a_sorted, 6)
top_5_correlated <- correlated %>%
  filter(Activo != "MEDICAB.MX" & Activo != "FEMSAUBD.MX")
print(top_5_correlated)
```
## Gráfico de rendimientos activos correlacionados 

```{r}
claves_top5 <- as.character(top_5_correlated[[1]])
claves_top5
```

```{r}
data <- new.env()
getSymbols(claves_top5, warnings = FALSE, env=data)

precio1 <- data[[claves_top5[[1]]]][,6]
Rend1 <- na.omit(diff(log(na.omit(precio1))))

precio2 <- data[[claves_top5[[2]]]][,6]
Rend2 <- na.omit(diff(log(na.omit(precio2))))

df_rend <- as.data.frame(Rend1)
df_rend

# Crear un dataframe inicial
df <- data.frame(
  Categorias = c("A", "B", "C", "D"),
  Valores = c(10, 20, 15, 25)
)

# Crear nuevas columnas
nuevas_columnas <- data.frame(NuevaColumna1 = c(1, 2, 3, 4),
                              NuevaColumna2 = c("X", "Y", "Z", "W"))

# Agregar las nuevas columnas al dataframe existente usando cbind()
df <- cbind(df, nuevas_columnas)

# Mostrar el dataframe actualizado
print(df)

```
```{r}
data[[claves_top5[[1]]]][,6]
```






