---
title: "Examen 2"
output: html_document
date: "2024-03-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(quantmod)
library(PerformanceAnalytics)
library(lubridate)
library(tidyverse)
library(moments)
library(TTR)
```


```{r}
clave <- "FEMSAUBD.MX"
datos <- new.env()
getSymbols(clave,from = "2000-01-03", to = "2024-03-14", env = datos)
precio <- na.omit(datos[[clave]][,6])
rend <- na.omit(diff(log(precio)))
rend_c <- rend^2 
```



## PROMEDIO MÓVIL CON PONDERACIONES CONSTANTES

$$\sigma^2(t,m) = \frac{1}{n}\sum_{i=1}^m[R^2_{t-i}]$$

```{r}
Var_5 <- SMA(rend_c,n=5)
Var_10 <- SMA(rend_c,n=10)
Var_20 <- SMA(rend_c,n=20)
Var_40 <- SMA(rend_c,n=40)
```



```{r}
layout(matrix(c(2,1)))
plot(rend_c, type="l")
plot(Var_5, type="l")
```
```{r}
# Trazar la primera gráfica
plot(rend_c, type="l", col="#040b5c", ylim=range(c(rend_c, Var_Esta_EWMA)), main="Gráficas juntas", ylab="Valor")
# Agregar la segunda gráfica al mismo eje y
lines(Var_5, type="l", col="blue")
```


### RMSE 

$$ RMSE = \sqrt{\frac{1}{H}\sum_{i=1}^m(R^2_{i} - \sigma^2_{I} )^2}$$

```{r}
Dif <-  merge.xts((rend_c-Var_5)^2, 
                    (rend_c-Var_10)^2,
                    (rend_c-Var_20)^2,
                    (rend_c-Var_40)^2)

names(Dif) <- c("m=5", "m=10","m=20", "m=40")
RMSE <- sqrt(colMeans(Dif, na.rm = TRUE))
RMSE
```

### EAMP

$$EAMP= \frac{1}{H}\sum_{i=1}^m|R^2_{i} - \sigma^2_{I}|$$


```{r}
Dif_2 <-  merge.xts(abs(rend_c-Var_5), 
                    abs(rend_c-Var_10),
                    abs(rend_c-Var_20),
                    abs(rend_c-Var_40))
names(Dif_2) <- c("m=5", "m=10","m=20", "m=40")
EAMP <- (colMeans(Dif_2, na.rm = TRUE))
EAMP
```
### ECPP

$$ ECPP = \sqrt{\frac{1}{H}\sum_{i=1}^m\left(\frac{R^2_{i} - \sigma^2_{I}}{R^2_{i}}\right)^2\right} $$
  

```{r}
Dif_3 <-  merge.xts(((rend_c-Var_5)/rend_c)^2, 
                    ((rend_c-Var_10)/rend_c)^2,
                    ((rend_c-Var_20)/rend_c)^2,
                    ((rend_c-Var_40)/rend_c)^2)
names(Dif_3) <- c("m=5", "m=10","m=20", "m=40")
Dif_3 <- subset(Dif_3, Dif_3$`m=5`!=Inf)
ECPP <- sqrt(colMeans(Dif_3, na.rm = TRUE))
ECPP
```
```{r}
m_optimo <- 5
Vol_Futura <- sqrt(mean(tail(rend_c, m_optimo)))*100
Vol_Futura
```

## EWMA

$$\sigma^2_t = (1-\lambda)R^2_{t-1}+\lambda \sigma^2_{t-1}$$

$$\sigma^2_t = (1-\lambda)R^2_{t-1}+\lambda \sigma^2_{t-1}$$

```{r}
n <- nrow(precio)
l <- seq(.0,.99, by=.01)
Var_Est <- matrix(0,nrow = (n-1) , ncol=1)
Func_Ver <- matrix(0,nrow = (n-1) , ncol=1)
Res <- matrix(0,ncol = 2, nrow = length(l))
Var_Est[1,1] <- rend_c[1,1]
j <- 0
for (L in l) {
  for(t in 2:(n-1)){
  Var_Est[t,1] <- (1-L)*rend_c[t-1,1]+L*Var_Est[t-1,1]
  Func_Ver[t,1] <- -log(Var_Est[t,1])-rend_c[t,1]/Var_Est[t,1]
  }
  j <- j+1
  Res[j,1] <- L
  Res[j,2] <- sum(Func_Ver)
}
```

```{r}
n <- nrow(precio)
l <- seq(.94,.96, by=.001)
Var_Est <- matrix(0,nrow = (n-1) , ncol=1)
Func_Ver <- matrix(0,nrow = (n-1) , ncol=1)
Res <- matrix(0,ncol = 2, nrow = length(l))
Var_Est[1,1] <- rend_c[1,1]
j <- 0
for (L in l) {
  for(t in 2:(n-1)){
  Var_Est[t,1] <- (1-L)*rend_c[t-1,1]+L*Var_Est[t-1,1]
  Func_Ver[t,1] <- -log(Var_Est[t,1])-rend_c[t,1]/Var_Est[t,1]
  }
  j <- j+1
  Res[j,1] <- L
  Res[j,2] <- sum(Func_Ver)
}
```



```{r}
Loptimo <- Res[order(Res[,2],decreasing = TRUE),][1,1]
Loptimo
```

$$\sigma^2_t = (1-.954)R^2_{t-1}+.954\sigma^2_{t-1}$$

```{r}
library(fTrading)
Var_Esta_EWMA <- xts(emaTA(rend_c, lambda = Loptimo),order.by = date(rend))
```
```{r}
Vol_futura <- as.numeric(sqrt((1-Loptimo)*rend_c[n-1,1] + Loptimo*Var_Esta_EWMA[n-1,1]))
Vol_futura
```
```{r}
layout(matrix(c(2,1)))
plot(rend_c,type="l", color = "#024f13")
plot(Var_Esta_EWMA, TYPE="L", color = "#48cc27")
```

```{r}
# Trazar la primera gráfica
plot(rend_c, type="l", col="#48cc27", ylim=range(c(rend_c, Var_Esta_EWMA)), main="Gráficas juntas", ylab="Valor")
# Agregar la segunda gráfica al mismo eje y
lines(Var_Esta_EWMA, type="l", col="#032b11")
```
## ARCH - GARCH

```{r}
rend <- na.omit(diff(log(precio)))

```


```{r}
ArchTest <- function (x, lags=20, demean = FALSE) 
{
  # Capture name of x for documentation in the output  
  xName <- deparse(substitute(x))
  # 
  x <- as.vector(x)
  if(demean) x <- scale(x, center = TRUE, scale = FALSE)
  #  
  lags <- lags + 1
  mat <- embed(x^2, lags)
  arch.lm <- summary(lm(mat[, 1] ~ mat[, -1]))
  STATISTIC <- arch.lm$r.squared * length(resid(arch.lm))
  names(STATISTIC) <- "Chi-squared"
  PARAMETER <- lags - 1
  names(PARAMETER) <- "df"
  PVAL <- 1 - pchisq(STATISTIC, df = PARAMETER)
  METHOD <- "ARCH LM-test;  Null hypothesis:  no ARCH effects"
  result <- list(statistic = STATISTIC, parameter = PARAMETER, 
                 p.value = PVAL, method = METHOD, data.name =
                   xName)
  class(result) <- "htest"
  return(result)
}
```
```{r}
ArchTest(rend)
```
```{r}
library(forecast)
tsdisplay(rend)
```
```{r}
Arch1 = garchFit(formula = ~garch(1,0), data=na.omit(rend),cond.dist="norm",trace=FALSE)
summary(Arch1)
```

```{r}
Arch2 = garchFit(formula = ~garch(2,0), data=na.omit(rend),cond.dist="norm",trace=FALSE)
summary(Arch2)
```
```{r}
garch11 = garchFit(formula = ~garch(1,1), data=na.omit(rend),cond.dist="norm",trace=FALSE)
summary(garch11)
```
```{r}
garch12 = garchFit(formula = ~garch(1,2), data=na.omit(rend),cond.dist="norm",trace=FALSE)
summary(garch12)
```

```{r}
garch21= garchFit(formula = ~garch(2,1), data=na.omit(rend),cond.dist="norm",trace=FALSE)
summary(garch21)
```



```{r}
garch22= garchFit(formula = ~garch(2,2), data=na.omit(rend),cond.dist="norm",trace=FALSE)
summary(garch22)
```

```{r}
Modelo_optimo <- garch11
```

```{r}
estimaciones <- predict(Modelo_optimo,n.ahead=500)

plot(estimaciones$standardDeviation,type="l")
```
```{r}
H <- summary(garch11)
sqrt(4.420e-06 /(1-7.368e-02 - 9.131e-01))
```
## MU NO CONSTANTE 

```{r}
auto.arima(rend)
```

*Aunque el arima recomendado es (2,0,2), ugarchfit tiene problemas para realizar el modelo, por lo que se utiliza (2,0,1) ya que los valores de AIC y de verosimilitud son casi iguales.

```{r}
especificaciones <- ugarchspec(mean.model = list(armaOrder=c(2,1)),
                               variance.model = list(model="sGARCH", garchOrder=c(1,1)))
```


```{r}
modelo <- ugarchfit(spec=especificaciones, data=rend)
modelo
```


```{r}
modelo@fit[["coef"]]
```

$$\sigma^2_t = 0.00000440509+0.073679R^2_{t-1}+0.913154 \sigma^2_{t-1}$$

$$\mu_t = 0.000724 + 0.930281R_{t-1}-0.035530R_{t-2}-0.916064\alpha_{t-1}$$

```{r}
gamma <- 1 - 0.073679 - 0.913154 
VL <- 0.000004405095/gamma
VL
```

Volatilidad

```{r}
sqrt(VL) * 100
```

```{r}
ugarchforecast(modelo, n.ahead = 200)
```

```{r}
forecast <- ugarchforecast(modelo, n.ahead = 200)
```

```{r}
plot(forecast@forecast[["sigmaFor"]], type="l")
```